platform :ios, '13.0'

flutter_application_path = '../fusion_flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
 
target 'fusion_ios' do
 install_all_flutter_pods(flutter_application_path)
end

# 添加编译配置
post_install do |installer|
  flutter_post_install(installer)
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['SWIFT_VERIFY_EMITTED_MODULE_INTERFACE'] = 'NO'
#    end
#  end
end

 
