platform :ios, '13.0'

flutter_application_path = '../fusion_flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
 
target 'fusion_ios' do
 install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer)
end
 
